apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-app-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-keycloak-app
  labels:
    app: python-keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-keycloak-app
  template:
    metadata:
      labels:
        app: python-keycloak-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-client-secrets.json: 'keycloak/client-secrets'
        vault.hashicorp.com/agent-inject-template-client-secrets.json: |
          {{ with secret "keycloak/client-secrets" -}}
          {
            "web": {
              "client_id": "{{ .Data.data.client_id }}",
              "client_secret": "{{ .Data.data.client_secret }}",
              "auth_uri": "{{ .Data.data.auth_uri }}",
              "token_uri": "{{ .Data.data.token_uri }}",
              "userinfo_uri": "{{ .Data.data.userinfo_uri }}",
              "issuer": "{{ .Data.data.issuer }}",
              "redirect_uris": ["{{ .Data.data.redirect_uris }}"],
              "flask_secret_key": "{{ .Data.data.flask_secret_key }}"
            }
          }
          {{- end }}
        vault.hashicorp.com/role: 'python-app'
    spec:
      serviceAccountName: python-app-sa
      containers:
      - name: python-app
        image: luhercen/python-keycloak-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: CLIENT_SECRETS_PATH
          value: "/vault/secrets/client-secrets.json"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000